site_name: Delivery Agent — Fingerprint

theme:
  name: material
  language: pt
  features:
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - toc.follow
    - content.code.copy

plugins:
  - search
  - mermaid2

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - def_list
  - attr_list
  - md_in_html

extra_css:
  - assets/impact.css

nav:
  - Overview: index.md
  - Clientes:
      - delivery-principal:
          - Visão geral: clients/delivery-principal/index.md
          - Grafo: clients/delivery-principal/grafo.md
          - Nós: clients/delivery-principal/nodes/index.md
          - Tabelas:
              - Conexões: clients/delivery-principal/tabelas/edges.md
              - Expressões: clients/delivery-principal/tabelas/expressions.md
              - SQL: clients/delivery-principal/tabelas/sql.md
              - Código: clients/delivery-principal/tabelas/code.md
          - Impacto: clients/delivery-principal/impacto.md
