site_name: Delivery Agent — Fingerprint

theme:
  name: material
  language: pt
  features:
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - toc.follow
    - content.code.copy

plugins:
  - search
  - mermaid2
  - awesome-pages

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - def_list
  - attr_list
  - md_in_html

extra_css:
  - assets/impact.css
