site_name: Delivery Agent — Fingerprint

theme:
  name: material
  language: pt

plugins:
  - search
  - mermaid2
  - awesome-pages

markdown_extensions:
  - admonition
  - toc

extra_css:
  - assets/impact.css
