site_name: Delivery Agent — Fingerprint
site_url: https://hub3ps.github.io/delivery-fingerprint/

theme:
  name: material
  language: pt
  features:
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - toc.follow
    - content.code.copy
    - content.code.annotate
    - content.action.view

repo_url: https://github.com/hub3ps/delivery-fingerprint
repo_name: hub3ps/delivery-fingerprint

plugins:
  - search
  - mermaid2
  - git-revision-date-localized:
      fallback_to_build_date: true
      enable_creation_date: false
      locale: pt_BR

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

extra_css:
  - assets/impact.css

nav:
  - Overview: index.md
  - Clientes:
      - delivery-principal:
          - Visão geral: clients/delivery-principal/index.md
          - Grafo: clients/delivery-principal/grafo.md
          - Nós: clients/delivery-principal/nodes/index.md
          - Tabelas:
              - Conexões: clients/delivery-principal/tabelas/edges.md
              - Expressões: clients/delivery-principal/tabelas/expressions.md
              - SQL: clients/delivery-principal/tabelas/sql.md
              - Código: clients/delivery-principal/tabelas/code.md
          - Impacto: clients/delivery-principal/impacto.md
